-- Seed: companies on Workday (Milestone 7). The adapter discovers each tenant's India filter from the list
-- facets, so config only says where the site is: POST https://{host}/wday/cxs/{tenant}/{site}/jobs.
-- India counts as seen on 2026-10-05/06 with the discovered filters (research/sources_2026-10-04.json has more).

INSERT INTO companies (slug, name, platform, config, careers_url, notes) VALUES
                                                                             ('nvidia',     'NVIDIA',     'workday',
                                                                              '{"host": "nvidia.wd5.myworkdayjobs.com", "tenant": "nvidia", "site": "NVIDIAExternalCareerSite"}',
                                                                              'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite',
                                                                              '242 India jobs. Country facet locationHierarchy1. Many hardware roles (ASIC, verification, physical design).'),
                                                                             ('mastercard', 'Mastercard', 'workday',
                                                                              '{"host": "mastercard.wd1.myworkdayjobs.com", "tenant": "mastercard", "site": "CorporateCareers"}',
                                                                              'https://mastercard.wd1.myworkdayjobs.com/CorporateCareers',
                                                                              '~210 India jobs. No country facet: city entries only (Pune, Gurgaon, Navi Mumbai...). "Remote - Indiana" must not match.'),
                                                                             ('salesforce', 'Salesforce', 'workday',
                                                                              '{"host": "salesforce.wd12.myworkdayjobs.com", "tenant": "salesforce", "site": "External_Career_Site"}',
                                                                              'https://salesforce.wd12.myworkdayjobs.com/External_Career_Site',
                                                                              '113 India jobs. Country facet has a long custom name.'),
                                                                             ('visa',       'Visa',       'workday',
                                                                              '{"host": "visa.wd5.myworkdayjobs.com", "tenant": "visa", "site": "Visa"}',
                                                                              'https://visa.wd5.myworkdayjobs.com/Visa',
                                                                              '80 India jobs. Country facet locationCountry.'),
                                                                             ('adobe',      'Adobe',      'workday',
                                                                              '{"host": "adobe.wd5.myworkdayjobs.com", "tenant": "adobe", "site": "external_experienced"}',
                                                                              'https://adobe.wd5.myworkdayjobs.com/external_experienced',
                                                                              '78 India jobs. Country facet locationCountry inside a facet group. A separate external_university site exists.'),
                                                                             ('intel',      'Intel',      'workday',
                                                                              '{"host": "intel.wd1.myworkdayjobs.com", "tenant": "intel", "site": "External"}',
                                                                              'https://intel.wd1.myworkdayjobs.com/External',
                                                                              '58 India jobs. City entries only (India, Bangalore + Virtual India). Many hardware roles.'),
                                                                             ('samsung',    'Samsung',    'workday',
                                                                              '{"host": "sec.wd3.myworkdayjobs.com", "tenant": "sec", "site": "Samsung_Careers"}',
                                                                              'https://sec.wd3.myworkdayjobs.com/Samsung_Careers',
                                                                              '31 India jobs (Location_Country). Samsung R&D Institute Bangalore; other Samsung India units may use other tenants.'),
                                                                             ('expedia',    'Expedia',    'workday',
                                                                              '{"host": "expedia.wd108.myworkdayjobs.com", "tenant": "expedia", "site": "search"}',
                                                                              'https://expedia.wd108.myworkdayjobs.com/search',
                                                                              '13 India jobs (Bangalore, Gurgaon city entries).'),
                                                                             ('paypal',     'PayPal',     'workday',
                                                                              '{"host": "paypal.wd1.myworkdayjobs.com", "tenant": "paypal", "site": "jobs"}',
                                                                              'https://paypal.wd1.myworkdayjobs.com/jobs',
                                                                              '11 India jobs (Bangalore, Chennai city entries).');